[tool.poetry]
name = "ancs4linux"
version = "1.0.0"
description = "Control your iOS device from Linux desktop"
authors = ["Paweł Zmarzły <pawo2500@gmail.com>"]
license = "GPL-2.0-or-later"
repository = "https://github.com/pzmarzly/ancs4linux"

[tool.poetry.scripts]
ancs4linux-observer = 'ancs4linux.observer.main:main'
ancs4linux-desktop-integration = 'ancs4linux.desktop_integration.main:main'
ancs4linux-ctl = 'ancs4linux.ctl.main:main'

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0.3"
dasbus = "^1.6"
PyGObject = "^3.42.0"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
mypy = "^0.910"
black = "^21.9b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
